# Generated by Django 4.2.1 on 2023-06-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="nombre_post",
        ),
        migrations.AddField(
            model_name="user",
            name="nombre_critique",
            field=models.IntegerField(default=0, verbose_name="Nombre de critique"),
        ),
        migrations.AddField(
            model_name="user",
            name="nombre_ticket",
            field=models.IntegerField(default=0, verbose_name="Nombre de ticket"),
        ),
    ]
