# Generated by Django 4.2.1 on 2023-06-27 16:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="abonnement",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
