# Generated by Django 4.2.1 on 2023-06-30 20:55

from django.db import migrations

def create_permission(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    content_type = ContentType.objects.get_for_model(Permission)  # Use Permission's ContentType as a placeholder

    Permission.objects.get_or_create(
        codename='gestion_utilisateur',
        defaults={
            'name': 'Can manage user',
            'content_type': content_type,
        },
    )

class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_user_abonnement"),  # Use the last migration of 'auth' app as a dependency
    ]

    operations = [
        migrations.RunPython(create_permission),
    ]

