# Generated by Django 4.2.1 on 2023-07-05 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_auto_20230701_0835"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="abonnement",
            field=models.ManyToManyField(
                to=settings.AUTH_USER_MODEL, verbose_name="follower"
            ),
        ),
    ]
