# Generated by Django 4.2.1 on 2023-07-08 05:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_alter_user_abonnement_userabonnement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="abonnement",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    {"UTILISATEUR", "Utilisateur"},
                    {"ADMINISTRATEUR", "Administrateur"},
                ],
                default="Utilisateur",
                max_length=30,
            ),
        ),
        migrations.DeleteModel(
            name="UserAbonnement",
        ),
    ]
