# Generated by Django 4.2.1 on 2023-07-03 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, max_length=2048)),
                (
                    "illustration",
                    models.ImageField(
                        default="../media/Pas_d'image_disponible.png", upload_to=""
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "nombre_critique",
                    models.IntegerField(default=0, verbose_name="Nombre de critique"),
                ),
                ("liste_contributeur", models.JSONField(null=True)),
                (
                    "auteur",
                    models.ForeignKey(
                        default="Demandeur inconnu",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Critique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "0"),
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "titre_critique",
                    models.CharField(
                        max_length=128, verbose_name="Titre de la critique"
                    ),
                ),
                ("commentaire", models.TextField(max_length=8192)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "auteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.ticket"
                    ),
                ),
            ],
        ),
    ]
