# Generated by Django 4.2.1 on 2023-06-13 10:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, max_length=2048)),
                (
                    "illustration",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "auteur",
                    models.ForeignKey(
                        default="Demandeur inconnu",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Critique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("titre", models.CharField(max_length=128)),
                ("commentaire", models.CharField(max_length=8192)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "auteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.ticket"
                    ),
                ),
            ],
        ),
    ]
