# Generated by Django 4.2.1 on 2023-06-11 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="critique",
            old_name="photo",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="image",
            old_name="uploader",
            new_name="auteur",
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="photo",
            new_name="image",
        ),
    ]
