# Generated by Django 4.2.1 on 2023-07-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="liste_contributeur",
            field=models.JSONField(default="NULL"),
            preserve_default=False,
        ),
    ]
