# Generated by Django 4.2.1 on 2023-06-11 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_rename_photo_critique_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="caption",
        ),
    ]
