# Generated by Django 4.2.1 on 2023-06-13 08:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0003_remove_image_caption"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Image",
            new_name="Illustration",
        ),
        migrations.RenameField(
            model_name="critique",
            old_name="image",
            new_name="illustration",
        ),
        migrations.RenameField(
            model_name="illustration",
            old_name="image",
            new_name="illustration",
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="image",
            new_name="illustration",
        ),
    ]
