# Generated by Django 4.2.1 on 2023-06-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_critique_nombre_critique"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="critique",
            name="nombre_critique",
        ),
        migrations.AddField(
            model_name="ticket",
            name="nombre_critique",
            field=models.IntegerField(default=0, verbose_name="Nombre de critique"),
        ),
    ]
