# Generated by Django 4.2.1 on 2023-06-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_remove_critique_nombre_critique_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="illustration",
            field=models.ImageField(
                default="../media/Pas_d'image_disponible.png", upload_to=""
            ),
        ),
    ]
