# Generated by Django 4.2.1 on 2023-06-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_rename_titre_critique_titre_critique_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="critique",
            name="commentaire",
            field=models.TextField(max_length=8192),
        ),
    ]
