# Generated by Django 4.2.1 on 2023-06-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_alter_critique_commentaire"),
    ]

    operations = [
        migrations.AlterField(
            model_name="critique",
            name="titre_critique",
            field=models.CharField(max_length=128, verbose_name="Titre de la critique"),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="titre_ticket",
            field=models.CharField(max_length=128, verbose_name="Titre du Ticket"),
        ),
    ]
